name: 'Example composite GitHub action'
description: 'Example composite GitHub action'
author: hello@cloudposse.com
branding:
  icon: 'file'
  color: 'white'
inputs:
  matrix-key:
    required: false
    description: "Matrix key"
  outputs:
    required: true
    description: "Outputs YAML structured map"
outputs:
  result:
    description: "Outputs result"
    value: "${{ steps.context.outputs.result }}"
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
      continue-on-error: true
      with:
        name: matrix-outputs
        path: ./matrix-outputs

    - shell: bash
      continue-on-error: true
      run: |
        ls -l ./
        ls -l ./matrix-outputs

    - shell: bash
      run: |
        mkdir -p ./matrix-outputs
        matrix=$((
          echo '${{ toJSON(inputs.outputs) }}'
        ) | jq -c .)
        echo "$matrix" > ./matrix-outputs/result.json
        echo "::set-output name=matrix::$matrix"
      id: matrix

    - shell: bash
      run: |
        ls -l ./
        ls -l ./matrix-outputs

    - uses: actions/upload-artifact@v3
      with:
        name: matrix-outputs
        path: ./matrix-outputs
        if-no-files-found: warn

    - shell: bash
      id: context
      run: |
        matrix="$(cat ./matrix-outputs/*.json | jq -c --slurp .)"
        echo "::set-output name=result::$matrix"

