name: 'Matrix outputs - write'
description: 'Write outputs for matrix'
author: hello@cloudposse.com
branding:
  icon: 'chevrons-up'
  color: 'white'
inputs:
  matrix-step-name:
    required: false
    description: "Matrix step name"
  matrix-key:
    required: false
    description: "Matrix key"
  outputs:
    required: false
    description: "YAML structured map of outputs"
outputs:
  result:
    description: "Outputs result (Deprecated!!!)"
runs:
  using: "node16"
  main: "index.js"
