name: 'Matrix outputs write'
description: 'Write outputs for matrix'
author: hello@cloudposse.com
branding:
  icon: 'chevrons-up'
  color: 'white'
inputs:
  matrix-step-name:
    required: false
    description: "Matrix step name"
  matrix-key:
    required: false
    description: "Matrix key"
  outputs:
    required: false
    description: "YAML structured map of outputs"
outputs:
  result:
    description: "Outputs result"
    value: "${{ steps.proxy.outputs.result }}"
runs:
  using: "composite"
  steps:
    - uses: nick-fields/assert-action@v1
      if: ${{ inputs.matrix-key != '' }}
      with:
        expected: ''
        actual: "${{ inputs.matrix-step-name }}"
        comparison: notEqual

    - uses: nick-fields/assert-action@v1
      if: ${{ inputs.matrix-step-name != '' }}
      with:
        expected: ''
        actual: "${{ inputs.matrix-key }}"
        comparison: notEqual

    - name: 'Install jq 1.6'
      uses: dcarbone/install-jq-action@v1.0.1
      with:
        version: 1.6
        force: 'true'

    - name: 'Setup yq'
      uses: dcarbone/install-yq-action@v1.0.0
      with:
        version: v4.28.1
        download-compressed: true
        force: true

    - shell: bash
      id: proxy
      run: |-
        JSON=$(echo "${{ inputs.outputs }}" | yq '. + {}' -o json | jq . -c -M -e)
        echo "result=${JSON}" >> $GITHUB_OUTPUT

    - uses: cloudposse/github-action-yaml-config-query@0.1.1
      id: mask
      with:
        query: .${{ inputs.matrix-key == '' }}
        config: |-
          true:
            mask: ". + {}"
          false:
            mask: "{\"${{ inputs.matrix-key}}\": . + {}}"

    - shell: bash
      id: write
      run: |-
        JSON=$(echo "${{ inputs.outputs }}" | yq '${{ steps.mask.outputs.mask }}' -o json | jq . -c -M -e)
        echo "result=${JSON}" >> $GITHUB_OUTPUT

    - shell: bash
      if: ${{ inputs.outputs != '' && inputs.matrix-step-name != '' }}
      run: |
        echo '${{ steps.write.outputs.result }}' > ${{ inputs.matrix-step-name }}
      id: matrix

    - uses: actions/upload-artifact@v3
      if: ${{ inputs.outputs != '' && inputs.matrix-step-name != '' }}
      with:
        name: ${{ hashFiles( inputs.matrix-step-name ) || 'none' }}
        path: ${{ inputs.matrix-step-name }}
        if-no-files-found: warn
