name: Test example positive
on:
#  # Uncomment when test added first time to register workflow and comment it back after workflow would be registered
#  #
#  # Added pull_request to register workflow from the PR.
#  # Read more https://stackoverflow.com/questions/63362126/github-actions-how-to-run-a-workflow-created-on-a-non-master-branch-from-the-wo
#  pull_request: {}
  workflow_dispatch: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["one", "two"]
    steps:
      - name: Setup
        run: echo "Do setup"

      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./
        id: writer
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.target }}
          outputs: |-
            result: ${{ matrix.target }}

      - uses: nick-fields/assert-action@v1
        with:
          expected: ${{ matrix.target }}
          actual: ${{ fromJson(steps.writer.outputs.result).result }}

  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [setup]
    steps:
      - uses: actions/download-artifact@v3

      - id: current
        run: |-
          echo "result=$(ls | wc -l)" >> $GITHUB_OUTPUT

    outputs:
      result: "${{ steps.current.outputs.result }}"

  assert:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: nick-fields/assert-action@v1
        with:
          expected: '2'
          actual: "${{ needs.test.outputs.result }}"


  teardown:
    runs-on: ubuntu-latest
    needs: [assert]
    if: ${{ always() }}
    steps:
      - name: Tear down
        run: echo "Do Tear down"
